# Usage example:
team_data = {
    0: ("Atlanta Hawks", "Large"),
    1: ("Boston Celtics", "Large"),
    2: ("Brooklyn Nets", "Very Large"),
    3: ("Charlotte Hornets", "Medium"),
    4: ("Chicago Bulls", "Very Large"),
    5: ("Cleveland Cavaliers", "Medium"),
    6: ("Dallas Mavericks", "Large"),
    7: ("Denver Nuggets", "Large"),
    8: ("Detroit Pistons", "Large"),
    9: ("Golden State Warriors", "Very Large"),
    10: ("Houston Rockets", "Large"),
    11: ("Indiana Pacers", "Medium"),
    12: ("Los Angeles Clippers", "Very Large"),
    13: ("Los Angeles Lakers", "Very Large"),
    14: ("Memphis Grizzlies", "Small"),
    15: ("Miami Heat", "Large"),
    16: ("Milwaukee Bucks", "Medium"),
    17: ("Minnesota Timberwolves", "Medium"),
    18: ("New Orleans Pelicans", "Small"),
    19: ("New York Knicks", "Very Large"),
    20: ("Oklahoma City Thunder", "Small"),
    21: ("Orlando Magic", "Medium"),
    22: ("Philadelphia 76ers", "Large"),
    23: ("Phoenix Suns", "Large"),
    24: ("Portland Trail Blazers", "Medium"),
    25: ("Sacramento Kings", "Medium"),
    26: ("San Antonio Spurs", "Medium"),
    27: ("Toronto Raptors", "Very Large"),
    28: ("Utah Jazz", "Small"),
    29: ("Washington Wizards", "Large"),
}
